server:
  port: 8689
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root1234
  application:
    name: dubbo-provider


dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    check: false
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 30000
  scan:
    base-packages: com.xxj.dubboprovider
#    protocol: zookeeper
#    check: false
  protocol:
    name: dubbo
    port: 12345
#  provider:
#    token: true
#  monitor:
#    protocol: register
#  consumer:
#    check: false
#    timeout: 3000
